apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-laravel
  template:
    metadata:
      labels:
        app: test-laravel
    spec:
      containers:
        - name: test-laravel
          image: iyedhosni743/test-laravel:latest
          ports:
            - containerPort: 80
