apiVersion: v1
kind: Service
metadata:
  name: crm-laravel-service
spec:
  selector:
    app: crm-laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
